flickr_api:
    path:       /flickr
    defaults:   { _controller: AppBundle:Flickr:index }
    methods:    [GET]

flickr_api_search:
    path:       /flickr/search
    defaults:   { _controller: AppBundle:Flickr:search }
    methods:    [POST]
    
flickr_api_search_pagination:
    path:       /flickr/search/{page}
    defaults:   { _controller: AppBundle:Flickr:search, page:null }
    methods:    [GET, POST]