flickr_api:
    path:       /flickr
    defaults:   { _controller: AppBundle:Flickr:index }
    methods:    [GET]

flickr_api_search:
    path:       /flickr/search
    defaults:   { _controller: AppBundle:Flickr:search }
    methods:    [POST]

flickr_api_search_pagination:
    path:       /flickr/search
    defaults:   { _controller: AppBundle:Flickr:search }
    methods:    [GET, POST]

flickr_api_get_photo:
    path:       /flickr/photo/{photo_id}
    defaults:   { _controller: AppBundle:Flickr:getPhoto }
    requirements:
      photo_id: '\d+'
    methods:    [GET]
